# vim: set ft=yaml ts=2 expandtab:
---

- name: Install bind named
  hosts: dns_group

  roles:
  - role: mafalb.bind.named
    bind_option_recursion: 'yes'
    bind_option_allow_query:
    - localnets
    bind_option_listen_on:
    - any
    bind_option_listen_on_v6:
    - any


- name: prepare client for CI
  hosts: client_group

  environment:
    http_proxy: http://ci_proxy:3128

  tasks:

  - name: bind utils are present
    package:
      name: bind-utils

...
