# vim: set ft=yaml ts=2 expandtab:
---

- name: prepare proxy
  hosts: proxy_group

  pre_tasks:

  # https://github.com/geerlingguy/ansible-role-composer/issues/54
  #
  - name: get status of systemd-tmpfiles-setup.service # noqa 303
    command: systemctl status systemd-tmpfiles-setup.service
    when: ansible_service_mgr == 'systemd'
    changed_when: false

  roles:
  - role: mafalb.squid.server
  - role: mafalb.bind.named
    bind_option_recursion: 'yes'
    bind_option_allow_query:
    - localnets
    bind_option_listen_on:
    - any
    bind_option_listen_on_v6:
    - any

...
