# vim: set ft=yaml ts=2 expandtab:
---

- name: verify resolver
  hosts: ci-client

  tasks:

  - name: our nameservers are present
    command: grep "nameserver {{ item }}" /etc/resolv.conf
    loop:
      - 10.92.185.146
      - fd5d:5ff6:1632:1::2
    changed_when: false

  - name: can resolve names
    command: host www.google.at
    changed_when: false

...
